
spring.datasource.url=jdbc:mysql://localhost:3306/POC-covoit
spring.datasource.username=POC-covoit
spring.datasource.password=POC-covoit

# JWT Configuration
jwt.secret=SuperSecretKeyForJWTTokenGenerationMakeItLongEnough123456789
jwt.expiration=86400000